### ISSUE TITLE
Any way to include this as a flat .js file on the client side?

### ISSUE THREAD

**Issue by jugglervr** [RGBboy/urlsafe-base64#6]
I'm not using node but need to encode some URIs safely. I'm having a little trouble figuring out how to flat-file this library. Any chance you could lend a hand?

**Comment by RGBboy** [comment]
Sure, what does "flat-file this library" mean?

**Comment by jugglervr** [comment]
I could have used the wrong terminology. I'd  like to see a single .js file that i can include on the client side without having to install with node, since I'm not using node. 
Might this be possible?

**Comment by RGBboy** [comment]
I don't think so. This module relies on nodes buffer module which will need to be shimmed and bundled to use this module. You would probably be better using something like https://github.com/duzun/base64util because it supports a standalone module format (AMD, Browser, CommonJs). I'm going to close this for now. If you have more questions keep asking.
